title: notes
description: notes of Joseph Lin.
url: "https://linjose.github.io" # e.g. https://yourname.github.io
baseurl: "/notes" # e.g. /blog when using project pages
author: linjose
lang: zh-TW
timezone: Asia/Taipei

markdown: kramdown
kramdown:
  input: GFM
permalink: /:categories/:year/:month/:day/:slug/
paginate: 8

# GitHub Pages uses a safe Jekyll build; avoid non-whitelisted plugins.
# We generate search.json without plugins using Liquid.
# theme: null
